### ISSUE TITLE
F3 wget on the notebook does not work

### ISSUE THREAD

**Issue by pythonmobile** [NVIDIA/energy-sdk#1]
Please fix.

**Comment by jpnavarro-nv** [comment]
Hi. It still works for me.
Can you please provide the environment you're running also the output error?

**Comment by pythonmobile** [comment]
Ubuntu 20.04LTS. The download code does not seem to work in bash or sh.
First line of code here: https://github.com/NVIDIA/energy-sdk/blob/master/rapids_seismic_facies/Unsupervised_Seismic_Facies_DGXA100.ipynb
Error: datasets/input/F3.sgy: No such file or directory

**Comment by jpnavarro-nv** [comment]
The link is still working for me on bash and inside the notebook. I couldn't reproduce your error. But please notice that data access directly from Google drive is not a long-term solution and we will change the data source in a near future. 

For now, you can download the data directly from the link https://docs.google.com/uc?export=download&id=1ZPsRasiCs1NfN72_Skn9YUgfipZ5KD4D

**Comment by pythonmobile** [comment]
can you please try it outside the notebook, in a bash or sh shell? See if that gives you the error?

Also, the new link you sent, that link does not work with wget either. Perhaps host the data on a website where wget is allowed?

**Comment by jpnavarro-nv** [comment]
Yes, I've tested on bash and it worked fine.
The link I've sent was to direct download, via web interface!

To download it via wget using a different command than the provided in the notebook, you will need an extra work:
https://stackoverflow.com/questions/25010369/wget-curl-large-file-from-google-drive
